### ISSUE TITLE
Change columns names

### ISSUE THREAD

**Issue by miofher11** [monofor/vue-tables-3#44]
Is there a way to change displayed name of the column from columns option?, without change object keys.

**Comment by DanielLusignan** [comment]
Use the heading property.
      
  headings: {

            [Column_Name_From_DataSet]: [Custom_name],
            [Column_Name_From_DataSet]: [Custom_name],
            [Column_Name_From_DataSet]: [Custom_name],
        },

**Comment by miofher11** [comment]
That's what I needed, thanks!
